* km-edit

Miscellaneous editing utils for Emacs.

** Installation

*** Manual

Download the source code and put it wherever you like, e.g. into =~/.emacs.d/km-edit/=

#+begin_src shell :eval no
git clone https://github.com/KarimAziev/km-edit.git ~/.emacs.d/km-edit/
#+end_src

Add the downloaded directory to the load path:

#+begin_src elisp :eval no
(add-to-list 'load-path "~/.emacs.d/km-edit/")
(require 'km-edit)
#+end_src

#+begin_src elisp :eval no
(use-package km-edit
  :straight (km-edit
             :repo "KarimAziev/km-edit"
             :type git
             :host github)
  :bind (("C-c TAB" . km-edit-indent-buffer-or-region)
         ("M-D" . km-edit-delete-line)
         ("C-c C-k" . km-edit-dwim-insert-key-description)
         ("C-a" . km-edit-smart-beginning-of-line)
         ("C-M-y" . km-edit-yank-pop-forwards)
         ("C-'" . km-edit-quote-or-unquote-at-point)))
#+end_src

** Commands

*** ~km-edit-recode-region~  (beg end)
Try all possible character encodings to re-decode region between =beg= and =end=. Show results in minibuffer completions and finally recode the region with selected one.
*** ~km-edit-copy-prin1-to-string-no-newlines~
Return a string with the printed representation of region without new lines.
*** ~km-edit-copy-prin1-to-string-at-point~
Return a string with the printed representation of active region or sexp.
*** ~km-edit-copy-sexp-or-region-at-point~
Copy region or sexp at point.
*** ~km-edit-dwim-insert-key-description~
Read and insert a description of keystrokes. Inside string also remove old content. If parent form is a symbol listed in =km-edit-dwim-kbd-forms= and point is not inside string, insert either vector or kbd call. In other cases insert string.
*** ~km-edit-quote-or-unquote-at-point~
Add or remove string quotes for thing at point.
*** ~km-edit-smart-beginning-of-line~
Move point to first non-whitespace character or beginning-of-line.
*** ~km-edit-recode-buffer-or-region~  (coding-system)
Encode and decode active region or whole buffer content to =coding-system=.
*** ~km-edit-delete-line~
Remove line without putting to kill ring.
*** ~km-edit-yank-pop-forwards~  (arg)
Call =yank-pop= with =arg= if the previous command was yank.
*** ~km-edit-indent-buffer-or-region~
Indent active region or the entire buffer.